apiVersion: v1
kind: Service
metadata:
  name:  spring-boot-snippet
  labels:
    app: spring-boot-snippet
spec:
  type:  LoadBalancer
  ports:
  - name:  http
    port:  8081 #local out port
    protocol: TCP
    targetPort:  80 # container port
  selector:
    app:  spring-boot-snippet #find all pod with app name
  sessionAffinity: None
